version: '3'
services:
    app:
        build: 
          context: ./
        volumes:
            - .:/go/src/github.com/jacky-htg/shonet-frontend
        working_dir: /go/src/github.com/jacky-htg/shonet-frontend
        ports:
            - "8080:8080"
        environment:
            - GOPATH=/go
        command: go run main.go
        links:
            - redis
            - mysql
    redis:
        container_name: redis
        image: "redis:alpine"
        ports:
            - "9379:6379" 
    mysql:
        container_name: mysql
        image: "mysql:5.5"
        ports:
            - "9306:3306"
        volumes:
            - ./docker_storage/dbdata:/var/lib
            - /etc/localtime:/etc/localtime
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=shonet_dev"
